
 Go to your car
 Drive to Sam's Club
 Search the produce section
 Grab an orange
 Pay for orange at the checkout
 Drive back to your home
 Open the tap and pour water to wash the orange
 Place the apple on the table
 Place an empty glass on the table
 Cut the orange horizontally into two equal halves
 Squeeze the juice from the first half of the orange with your hand into the glass
 Squeeze out the juice from the second half of the orange with your hand into a glass
 Yellow liquid that collects in the glass is your orange juice
